"""Stable taxonomy/configuration view over the sports engine.

This module gives taxonomy consumers a focused import surface without changing
sports.py behavior. The large sports engine remains the compatibility source of
truth in this first behavior-preserving refactor pass.
"""

import sports as _sports


DEFAULT_SETTINGS = _sports.DEFAULT_SETTINGS
SCHEDULE_API_KEY_SETTING = _sports.SCHEDULE_API_KEY_SETTING
SCHEDULE_API_PROVIDER_NAME = _sports.SCHEDULE_API_PROVIDER_NAME
SCHEDULE_API_PROVIDER_URL = _sports.SCHEDULE_API_PROVIDER_URL
SCHEDULE_API_SOURCE = _sports.SCHEDULE_API_SOURCE
SCHEDULE_API_LEAGUE_ID = _sports.SCHEDULE_API_LEAGUE_ID
SCHEDULE_API_REMOTE_LEAGUE_ID = _sports.SCHEDULE_API_REMOTE_LEAGUE_ID
SCHEDULE_API_DATASETS = _sports.SCHEDULE_API_DATASETS
SCHEDULE_API_DATASET_BY_LEAGUE = _sports.SCHEDULE_API_DATASET_BY_LEAGUE
SCHEDULE_API_DATASETS_BY_SPORT = _sports.SCHEDULE_API_DATASETS_BY_SPORT
SCOPE_TYPES = _sports.SCOPE_TYPES
RULE_PRIORITY = _sports.RULE_PRIORITY
SPORT_DEFINITIONS = _sports.SPORT_DEFINITIONS
LEAGUE_DEFINITIONS = _sports.LEAGUE_DEFINITIONS
SPORT_NAMES = _sports.SPORT_NAMES
SPORT_PATTERNS = _sports.SPORT_PATTERNS
LEAGUE_NAMES = _sports.LEAGUE_NAMES
LEAGUE_SPORTS = _sports.LEAGUE_SPORTS
LEAGUE_PATTERNS = _sports.LEAGUE_PATTERNS
LEAGUE_BLOCK_ORDER = _sports.LEAGUE_BLOCK_ORDER
LEAGUE_BLOCK_INDEX = _sports.LEAGUE_BLOCK_INDEX
LEAGUE_BLOCK_SIZE = _sports.LEAGUE_BLOCK_SIZE
OVERFLOW_BLOCK_OFFSET = _sports.OVERFLOW_BLOCK_OFFSET
COLLEGE_FOOTBALL_LEAGUES = _sports.COLLEGE_FOOTBALL_LEAGUES
TEAM_MATCHUP_LEAGUES = _sports.TEAM_MATCHUP_LEAGUES
REPLAY_RE = _sports.REPLAY_RE
PREGAME_RE = _sports.PREGAME_RE
SCHEDULE_API_LIVE_CANDIDATE_WINDOW = _sports.SCHEDULE_API_LIVE_CANDIDATE_WINDOW
SCHEDULE_API_MATCH_WINDOW = _sports.SCHEDULE_API_MATCH_WINDOW
SCHEDULE_API_SUPPORT_RE = _sports.SCHEDULE_API_SUPPORT_RE
PLACEHOLDER_RE = _sports.PLACEHOLDER_RE
CLEAR_OFF_AIR_RE = _sports.CLEAR_OFF_AIR_RE
DATE_RE = _sports.DATE_RE
MATCHUP_RE = _sports.MATCHUP_RE
EVENT_VARIANT_RE = _sports.EVENT_VARIANT_RE
LEADING_TIME_RE = _sports.LEADING_TIME_RE
MLB_TEAMS = _sports.MLB_TEAMS
MLB_ALIASES_BY_NAME = _sports.MLB_ALIASES_BY_NAME
CONFERENCE_TEAMS = _sports.CONFERENCE_TEAMS
SEED_CATALOG = _sports.SEED_CATALOG
LEGACY_DEMO_RULES = _sports.LEGACY_DEMO_RULES
TEAM_FEED_PATTERNS = _sports.TEAM_FEED_PATTERNS
NETWORK_WORDS = _sports.NETWORK_WORDS

__all__ = [name for name in globals() if name.isupper()]
